### ISSUE TITLE
Will the code be open source?

### ISSUE THREAD

**Issue by Henry0528** [HiHiAllen/Chip-surface-defect-dataset#1]

**Comment by JaneJJZhang** [comment]
Hello, my friends and I download zip directly on the computer, the result of the picture can not preview, but only download a separate picture can preview, could you please share the zip to me? Email: 1761244795@qq.com.Thanks.

**Comment by HiHiAllen** [comment]
Thank you for your interest in this work. Apologies, but this is a project in collaboration with a company, so the code cannot be open-sourced. However, the paper provides a detailed description of the network architecture and processing steps, making it not difficult to reproduce.
From my perspective, this work is from two years ago, and there are now better options for the construction of simulation data and network selection mentioned in the paper. Perhaps you could try updating some of the key modules with newer technologies?
