### ISSUE TITLE
how to increase your lfs quota?

### ISSUE THREAD

**Issue by liaocs2008** [HiHiAllen/Chip-surface-defect-dataset#4]
Hi there,

thanks for sharing the data. it looks like your lfs quota is limited, and downloading the dataset will fail. can you share the data in another way, like google drive or something? or you can share a donation link for people who are interested and willing to pay for downloading service.

**Comment by HiHiAllen** [comment]
Hi. The Git LFS quota is full, so I re-uploaded the dataset to Google Drive. Here is the link: https://drive.google.com/file/d/1_L7ovWgIBD15Tr5GqzKLJlNCYMVCJvBB/view?usp=drive_link
